# Generated by Django 4.2.8 on 2023-12-19 06:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('task_type', models.CharField(choices=[('bug', 'Bug'), ('feature', 'Feature'), ('task', 'Task')], max_length=10)),
                ('status', models.CharField(choices=[('new', 'New')], default='new', max_length=10)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('percent_done', models.IntegerField()),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
