# Generated by Django 4.2.8 on 2023-12-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_number',
            field=models.CharField(default='#100', editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
